import HautevilleHouse.NeuroscienceAttentionCognitionTheoremCanonicalLaneLean.HodgkinHuxleyDynamics
import HautevilleHouse.NeuroscienceAttentionCognitionTheoremCanonicalLaneLean.HebbianPlasticity
import HautevilleHouse.NeuroscienceAttentionCognitionTheoremCanonicalLaneLean.NeuralFieldTheory
import HautevilleHouse.NeuroscienceAttentionCognitionTheoremCanonicalLaneLean.AttentionalSelection
import HautevilleHouse.NeuroscienceAttentionCognitionTheoremCanonicalLaneLean.ConnectomicsEvidence
import HautevilleHouse.NeuroscienceAttentionCognitionTheoremCanonicalLaneLean.CognitiveControlBridge

namespace HautevilleHouse
namespace NeuroscienceAttentionCognitionTheoremCanonicalLaneLean

theorem all_domains_imported : True := trivial

end NeuroscienceAttentionCognitionTheoremCanonicalLaneLean
end HautevilleHouse